language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
services:
  - docker
env:
  - DOCKER_REPO_SLUG=plantlogic/frontend
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - ng lint
  - ng build --prod
  - docker build -t $DOCKER_REPO_SLUG:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO_SLUG;
    fi
